export const profile = {
  name: "Gautam Balgi",
  fullName: "Gautam Krishna Balgi",
  email: "balgigautam604@gmail.com",
  phone: "+1 (315) 418-9980",
  location: "New York, USA",
  linkedin: "https://linkedin.com/in/gautam-balgi/",
  github: "https://github.com/gautambalgi",
  tagline: "AI & Data Scientist building intelligent systems",
  summary:
    "I am an AI and Machine Learning Engineer currently pursuing my MS in Applied Data Science at Syracuse University, where I focus on building end-to-end intelligent systems that translate research into real-world impact. My work spans large-scale NLP, LLM evaluation, model optimization, and designing reproducible experimentation pipelines across structured and unstructured data.",
  longBio: [
    "I am an AI and Machine Learning Engineer currently pursuing my MS in Applied Data Science at Syracuse University, where I focus on building end-to-end intelligent systems that translate research into real-world impact. My work spans large-scale NLP, LLM evaluation, model optimization, and designing reproducible experimentation pipelines across structured and unstructured data.",
    "At HomeInheritance Inc, an early-stage and rapidly growing AI-driven startup, I worked as an AI and Data Science Intern, where I engineered scalable data pipelines and built a Retrieval Augmented Generation based internal knowledge assistant using LangChain, Pinecone, and OpenAI APIs. I worked on optimizing model workflows, improving inference efficiency, and supporting the deployment of ML-powered features into production systems.",
    "Through my research at NEXIS Labs and Syracuse University, I have designed transformer-based NLP systems using BERT and related architectures, evaluated large language models through structured experimental frameworks, and developed benchmarking workflows focused on responsible AI and performance validation.",
    "I am actively seeking full-time opportunities starting in 2026 in Data Analytics, Data Science, AI, and Machine Learning engineering, and Software Development roles, where I can design data-driven solutions and contribute to building scalable, production-ready systems.",
  ],
};

export const education = [
  {
    school: "Syracuse University",
    location: "New York, USA",
    degree: "Master of Science, Applied Data Science",
    school_unit: "School of Information Studies",
    period: "Aug 2024 · May 2026",
    cgpa: "3.86 / 4.00",
    coursework: [
      "Applied Machine Learning",
      "Natural Language Processing",
      "Quantitative Analysis",
      "Deep Learning",
      "Human-Centered AI",
    ],
  },
  {
    school: "Manipal Institute of Technology",
    location: "Manipal, India",
    degree: "B.Tech, Automobile Engineering (Minor in Computing)",
    period: "Aug 2019 · Jun 2023",
    coursework: ["Probability", "Linear Optimization", "Machine Learning"],
  },
];

export const experience = [
  {
    company: "HomeInheritance Inc.",
    role: "AI & Data Science Intern",
    location: "Miami, FL",
    period: "Jun 2025 · Dec 2025",
    type: "Internship",
    accent: "coral",
    tags: ["RAG", "LLMs", "Data Pipelines", "Tableau", "LangChain", "Pinecone"],
    bullets: [
      "Designed Python-based backend services to ingest, normalize, and serve unstructured text, image, and log data, improving platform data readiness by 37% and reducing downstream ML pipeline latency by 24%.",
      "Delivered a full-stack internal application by owning backend APIs and frontend integration, embedding a retrieval-augmented AI assistant that automated employee workflows and reduced information retrieval time by 47%.",
      "Architected scalable data-processing and inference pipelines using batching and vectorization strategies, enabling higher-throughput execution and faster rollout of ML-powered product features.",
      "Instrumented application-level analytics with Python and SQL to surface backend performance bottlenecks and user-interaction friction points, driving an 18% increase in overall feature engagement.",
      "Automated 55% of recurring business queries through the RAG-based internal chatbot deployment.",
    ],
  },
  {
    company: "NEXIS Labs · Syracuse University",
    role: "Graduate Student Researcher",
    location: "Syracuse, NY",
    period: "Aug 2024 · Dec 2025",
    type: "Research",
    accent: "violet",
    tags: ["NLP", "BERT", "Sentiment Analysis", "Behavioral Analytics"],
    bullets: [
      "Implemented BERT-based sentiment modeling on 50,000+ tweets about the 2024 USA election with structured preprocessing and feature engineering, achieving 85% accuracy and increasing dataset reliability by 30%.",
      "Enhanced AI-driven video personalization across 10+ content categories in the MindFeed app through engagement analysis, improving recommendation relevance by 22% and strengthening user retention.",
      "Leveraged statistical modeling with Python (Matplotlib, Pandas) to uncover sentiment trends, increasing trend detection accuracy by 25% and highlighting key shifts in public opinion.",
    ],
  },
  {
    company: "Syracuse University · School of Information Studies",
    role: "Graduate Research Assistant",
    location: "Syracuse, NY",
    period: "May 2025 · Aug 2025",
    type: "Research",
    accent: "amber",
    tags: ["LLM Evaluation", "Fine-tuning", "Transformer Optimization"],
    bullets: [
      "Standardized and validated 56,000+ text records using Python to ensure data integrity for large-scale LLM validation and downstream psychological text analysis.",
      "Executed controlled inference experiments across multiple LLM configurations, evaluating 10+ prompting strategies (zero/few-shot, A/B testing) and improving prediction accuracy by 28%.",
      "Automated model-to-human output comparison workflows, reducing manual evaluation time by 41% while maintaining 81% agreement with annotated benchmarks.",
      "Optimized transformer-based inference pipelines to improve classification accuracy by 19% and reduce GPU memory consumption by 22%.",
      "Fine-tuned open-source LLMs (LLaMA, Mistral) on custom datasets and benchmarked against proprietary AI (GPT-4) using F1 scores.",
    ],
  },
  {
    company: "Syracuse University · Whitman School of Management",
    role: "Graduate Research Assistant",
    location: "Syracuse, NY",
    period: "Feb 2025 · Aug 2025",
    type: "Research",
    accent: "moss",
    tags: ["Research", "Cost Modeling", "Policy Analysis"],
    bullets: [
      "Conducted in-depth analysis of SUNY Oswego's on- and off-campus housing costs, covering rent, utilities, meals, transportation, and financial aid limitations.",
      "Evaluated housing policies and student residency requirements to understand their impact on housing expenses.",
      "Built structured comparison models, created cost breakdown visuals, presented findings at the BRC Conference, and drafted a research paper incorporating institutional data.",
    ],
  },
  {
    company: "LTIMindtree",
    role: "Data Analyst Trainee / Intern",
    location: "Mumbai, India",
    period: "Jan 2023 · Dec 2023",
    type: "Industry",
    accent: "violet",
    tags: ["MySQL", "Python", "Tableau", "Random Forest"],
    bullets: [
      "Extracted and analyzed 100K+ records using MySQL to support business analytics initiatives, reducing reporting turnaround time by 25%.",
      "Collaborated with a team of 12 to process data using MySQL and Tableau for creating interactive dashboards that streamlined workflows.",
      "Automated Python-based data validation processes using custom scripts, increasing dataset reliability by 35% and reducing manual data cleaning effort.",
      "Developed predictive models using the Random Forest algorithm in Python, refining variables to achieve 86% forecast accuracy.",
    ],
  },
  {
    company: "Mercedes-Benz AG",
    role: "After-Sales Intern",
    location: "Goa, India",
    period: "Jun 2022 · Jul 2022",
    type: "Industry",
    accent: "moss",
    tags: ["Diagnostics", "Customer Engagement"],
    bullets: [
      "Performed maintenance on 50+ vehicles, including oil changes and brake inspections, to ensure optimal performance.",
      "Diagnosed and resolved issues in 15+ vehicles, focusing on engines and electronic systems.",
      "Addressed post-delivery concerns for 20+ customers, strengthening problem-solving and stakeholder skills.",
    ],
  },
];

export const projects = [
  {
    slug: "ethics-aware-betting",
    title: "Ethics-Aware Sports Betting ML System",
    period: "Aug 2025 · Dec 2025",
    github: null,
    summary:
      "End-to-end AI decision pipeline combining XGBoost calibration, Deep Q-Network behavior modeling, and a DeBERTa-based responsible-AI ethics layer.",
    stack: ["XGBoost", "Deep Q-Network", "DeBERTa", "LLMs", "Python", "PyTorch"],
    accent: "coral",
    bullets: [
      "Constructed an end-to-end predictive system using XGBoost trained on 2.7M RetailRocket events, 100K betting records, and 50K user interactions, improving probability calibration by 22%.",
      "Trained a reinforcement-learning behavior module using a Deep Q-Network on 25,000 interaction transitions with a 50K replay buffer, increasing long-term behavior stability by 31%.",
      "Integrated real-time Odds API services with prediction pipelines across 14+ match variables, improving transparency alignment between bookmaker odds and model probabilities by 27%.",
      "Developed an ethics-filtering subsystem using DeBERTa, reducing unsafe system actions from 7% to 0.3% while increasing balanced response rates to 84.5%.",
    ],
    impact: ["2.7M+ events processed", "Unsafe actions: 7% to 0.3%", "+22% probability alignment"],
  },
  {
    slug: "smart-grocery-detection",
    title: "Smart Grocery Detection & Recommendation",
    period: "Jan 2025 · May 2025",
    github: "https://github.com/gautambalgi/SmartGrocerySystem",
    summary:
      "YOLOv5-based computer vision pipeline for real-time grocery detection paired with a top-5 recommendation engine.",
    stack: ["YOLOv5", "PyTorch", "Computer Vision", "CUDA"],
    accent: "amber",
    bullets: [
      "Led development of a YOLOv5-based computer-vision service trained on 10,000+ images, achieving 86% accuracy across 15 product categories.",
      "Designed a frequent-purchase recommendation engine that improved recommendation relevance by 25% and increased retailer sales potential.",
      "Accelerated GPU-based inference workflows, reducing real-time latency by 32% and increasing throughput for production deployment.",
    ],
    impact: ["10K+ images trained", "86% detection accuracy", "32% lower inference latency"],
  },
  {
    slug: "emotion-aware-voice",
    title: "Emotion-Aware Personalized Voice Messaging",
    period: "Jan 2025 · May 2025",
    github: "https://github.com/gautambalgi/Emotion-Aware-Personalized-Voice-Messaging-System",
    summary:
      "End-to-end emotion-aware voice pipeline using a 27-class GoEmotions classifier and three benchmarked TTS models.",
    stack: ["GoEmotions", "Jenny TTS", "Bark", "Zonos", "PyTorch"],
    accent: "violet",
    bullets: [
      "Built an emotion-classification pipeline using a GoEmotions-based model covering 27 emotion categories, enabling structured emotional signal extraction.",
      "Benchmarked emotion-aware text-to-speech systems (Jenny, Bark, Zonos) across five emotional conditions to guide expressive model selection.",
      "Quantified speech clarity, emotional alignment, and tonal variation across 50+ generated samples, improving emotion-to-speech mapping accuracy by 22%.",
    ],
    impact: ["27 emotion classes", "3 TTS models benchmarked", "+22% alignment"],
  },
  {
    slug: "sc-energy-demand",
    title: "South Carolina Energy Demand Analysis",
    period: "Aug 2024 · Dec 2024",
    github: "https://github.com/gautambalgi/South-Carolina-Weather-Analysis",
    summary:
      "Statistical and ML analysis of energy usage across 5,000+ households with interactive Shiny dashboards visualizing peak-demand drivers.",
    stack: ["R", "Shiny", "Statistical Modeling", "Hypothesis Testing"],
    accent: "moss",
    bullets: [
      "Analyzed energy usage for 5,000+ households and reduced 140+ variables to 42 significant drivers using correlation and hypothesis testing.",
      "Built interactive Shiny dashboards to visualize peak-demand drivers and blackout risk scenarios.",
    ],
    impact: ["5,000+ households", "140 to 42 variables", "Blackout-risk modeling"],
  },
  {
    slug: "elearning-db",
    title: "E-Learning Database Management System",
    period: "Aug 2024 · Dec 2024",
    github: "https://github.com/gautambalgi/E-Learning-Database-Management-Sysytem",
    summary:
      "Normalized relational database with SQL reporting queries and Power BI dashboards visualizing course completion and learner performance.",
    stack: ["SQL", "Azure Data Studio", "Power BI"],
    accent: "amber",
    bullets: [
      "Designed and implemented a normalized relational database with 8+ structured tables to manage user, course, enrollment, and performance data across 500+ records.",
      "Built SQL-based reporting queries and interactive Power BI dashboards visualizing completion rates, scores, and active users, reducing manual reporting effort by 30%.",
    ],
    impact: ["8+ normalized tables", "500+ records", "30% less reporting effort"],
  },
];

export const skills = {
  Languages: ["Python", "R", "SQL", "TypeScript", "C++", "MongoDB"],
  "Machine Learning & AI": [
    "PyTorch",
    "TensorFlow",
    "Scikit-learn",
    "Hugging Face Transformers",
    "BERT",
    "RoBERTa",
    "T5",
    "DeBERTa",
    "LSTM",
    "XGBoost",
  ],
  "LLMs & Generative AI": [
    "GPT-3.5/4",
    "Claude",
    "Mistral",
    "LLaMA",
    "RAG",
    "LangChain",
    "Pinecone",
    "OpenAI APIs",
    "Agentic Orchestration",
    "Prompt Engineering",
  ],
  "Data Analytics & Viz": [
    "Tableau",
    "Power BI",
    "Shiny",
    "Statistical Analysis",
    "A/B Testing",
    "Forecasting",
    "Data Storytelling",
  ],
  "Backend & Systems": [
    "REST APIs",
    "Data Pipelines",
    "ETL/ELT",
    "Snowflake",
    "Git",
    "ONNX",
    "CUDA",
    "TensorRT",
    "vLLM",
    "SGLang",
  ],
  "Cloud & DevOps": ["AWS", "Azure", "GCP", "Docker", "Kubernetes", "CI/CD"],
};

export const stats = [
  { value: "3.86", label: "Graduate CGPA", suffix: "/4.0" },
  { value: "5+", label: "ML / AI Projects" },
  { value: "2.7M", label: "Events Modeled", suffix: "+" },
  { value: "85%", label: "BERT Accuracy" },
];